spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-github-username/olx-config
          username: your-github-username
          password: xxx
          clone-on-start: true
          
server:
  port: 8888
